name: Docker Images CI

on:
  push:
    branches: [ main ]

jobs:
  ci-go:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build GOlang docker CI/CD image
      run: docker build ./go/ --file go/Dockerfile --tag consulthink/go-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/go-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/go-builder:latest

  ci-php:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build PHP docker CI/CD image
      run: docker build ./php/ --file php/Dockerfile --tag consulthink/php-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/php-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/php-builder:latest

  ci-maven:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Java/maven docker CI/CD image
      run: docker build ./maven/ --file maven/Dockerfile --tag consulthink/maven-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/maven-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/maven-builder:latest

  ci-android:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Android/gradle docker CI/CD image
      run: docker build ./android-sdk/ --file android-sdk/Dockerfile --tag consulthink/android-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/android-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/android-builder:latest

  ci-qa:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build QA checker docker CI/CD image
      run: docker build ./qa/ --file qa/Dockerfile --tag consulthink/qa-checker:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/qa-checker:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/qa-checker:latest
