name: Docker Images CI

on:
  push:
    branches: [ main ]

jobs:
  ci-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build GOlang docker-builder image
      run: docker build ./go-1.16.0-buster/ --file go-1.16.0-buster/Dockerfile --tag consulthink/go-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/go-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/go-builder:latest

  ci-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build PHP docker-builder image
      run: docker build ./php-7.4-buster/ --file php-7.4-buster/Dockerfile --tag consulthink/php-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/php-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/php-builder:latest

  ci-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Java/maven docker-builder image
      run: docker build ./maven-3.6-buster/ --file maven-3.6-buster/Dockerfile --tag consulthink/maven-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/maven-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/maven-builder:latest

  ci-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Android/gradle docker-builder image
      run: docker build ./android-sdk-buster/ --file android-sdk-buster/Dockerfile --tag consulthink/android-builder:latest
    - name: Login to Consulthink registry (docker hub)
      run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Push to Consulthink registry (docker hub)
      run: docker push consulthink/android-builder:latest
    - name: Cleanup
      run: docker logout && docker rmi consulthink/android-builder:latest
