name: QA and OPS pipeline

on:
  push:
    branches:
      - '*'

jobs:
  qa:
    name: QA - check Dockerfiles syntax
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker CI/CD image
        run: |
          docker build ./base/ --file ./base/Dockerfile --tag "lukecottage/base-ops:latest"
          docker build ./go/ --file ./base/Dockerfile --tag "lukecottage/go-ops:latest"
          docker build ./php/ --file ./base/Dockerfile --tag "lukecottage/php-ops:latest"
          docker build ./java/ --file ./base/Dockerfile --tag "lukecottage/kava-ops:latest"

  kics:
    runs-on: ubuntu-20.04
    name: QA - KICS scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create folder output - results-dir
        run: mkdir -p results-dir

      - name: Create KICS config
        run: |
          cat <<EOF >>kics.config
          {
            "exclude-categories": "Encryption",
            "log-file": true,
            "minimal-ui": false,
            "no-color": false,
            "no-progress": true,
            "output-path": "./reports",
            "output-name": "results",
            "report-formats": "json,sarif",
            "type": "Dockerfile",
            "silent": true
          }
          EOF

      - name: Run KICS Scan (using configfile)
        continue-on-error: true
        uses: checkmarx/kics-action@v1.4
        with:
          path: '.'
          config_path: ./kics.config

      - name: DEBUG - check if files exists
        run: |
          ls -lah .
          ls -lah ./reports


      - name: Upload SARIF file (Github CodeQL)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./reports/results.sarif
