name: QA and OPS pipeline

on:
  schedule:
    - cron: '0 12 10 2,4,6,8,10,12 *'
  push:
    branches:
      - 'main'
      - 'develop'

env:
  docker_image_name: 'lukecottage/ops-image'
  docker_image_version: latest
  docker_file_iac: Dockerfile

jobs:
  qa-base:
    name: QA - verify and deploy latest version (no tag)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker CI/CD image
        run: docker build ./ --file ./$docker_file_iac --build-arg DEVMODE="no" --tag "${docker_image_name}:${docker_image_version}"
      - name: Login to registry (docker hub)
        run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push to registry (docker hub)
        run: docker push "${docker_image_name}:${docker_image_version}"

  kics:
    name: QA - KICS scan
    runs-on: ubuntu-latest
    container: checkmarx/kics:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create report folder output
        run: mkdir -p ./reports

      # see: https://docs.kics.io/latest/commands/
      #--exclude-categories Encryption
      - name: Run KICS scan
        run: kics scan --no-progress --ci
              --ignore-on-exit all
              --type Dockerfile
              --report-formats json,sarif
              --output-name results
              --output-path ./reports
              --path ./

      - name: DEBUG - check if files exists
        run: |
          ls -lah .
          ls -lah ./reports

      - name: Upload SARIF file (Github CodeQL)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./reports/results.sarif
