name: Release Docker images pipeline

on:
  push:
    #branches: [ main ]
    tags:
      - '*'
      - '**'

jobs:
  ci-base:
    name: OPS - create BASE docker image
    env:
      docker_image_name: 'lukecottage/ops-image'
      docker_image_version: latest
      docker_file_iac: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env RELEASE_VERSION from GIT-TAG ref
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build docker CI/CD image
        run: |
          docker build ./ --file ./$docker_file_iac \
            --tag "${docker_image_name}:${docker_image_version}" \
            --tag "${docker_image_name}:${{ env.RELEASE_VERSION }}"
      - name: Login to registry (docker hub)
        run: docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push to registry (docker hub)
        run: |
          docker push "${docker_image_name}:${docker_image_version}"
          docker push "${docker_image_name}:${{ env.RELEASE_VERSION }}"